# frozen_string_literal: true

require "active_support/concern"

module MaquinaStream
  # Host contract for a streamable record. The host owns persistence; the
  # engine never guesses a broadcast target and never invents authorization.
  #
  #   class Message < ApplicationRecord
  #     include MaquinaStream::Streamable
  #     maquina_stream buffer: :content,
  #                    stream_for: ->(m) { [m.conversation, :messages] }
  #   end
  #
  # The macro generates the seven contract methods when the column names match
  # (see docs/engine-contract.md). Anything the host defines itself wins, and
  # a method whose backing column is missing raises ContractError naming it.
  module Streamable
    extend ActiveSupport::Concern

    SEQUENCE_COLUMN = :stream_sequence
    STATUS_COLUMN = :stream_status
    OPEN_STATUS = "open"
    # A stream that timed out is not the same as one that errored: nothing went
    # wrong, the model simply stopped answering, and the partial text it did
    # produce is still worth keeping and replaying.
    SEAL_STATUSES = %i[complete cancelled errored timed_out].freeze

    CONTRACT_METHODS = %i[
      maquina_stream_id
      maquina_stream_buffer
      maquina_stream_append
      maquina_stream_sequence
      maquina_stream_advance
      maquina_stream_open?
      maquina_stream_seal!
      maquina_stream_target
    ].freeze

    included do
      class_attribute :maquina_stream_buffer_column, instance_writer: false
      class_attribute :maquina_stream_target_resolver, instance_writer: false
    end

    class_methods do
      def maquina_stream(buffer:, stream_for:)
        self.maquina_stream_buffer_column = buffer.to_sym
        self.maquina_stream_target_resolver = stream_for

        include Generated
      end

      # Names the contract methods this class cannot satisfy — the generated
      # ones whose column is missing and that the host has not defined itself.
      def maquina_stream_contract_gaps
        Generated.instance_methods.filter_map do |method|
          column = Generated::REQUIRED_COLUMNS[method]
          next if column.nil?

          column = maquina_stream_buffer_column if column == :buffer
          method unless maquina_stream_column?(column)
        end
      end

      def maquina_stream_column?(column)
        column_names.include?(column.to_s)
      rescue ActiveRecord::StatementInvalid, ActiveRecord::NoDatabaseError
        false
      end
    end

    # Generated by the macro. Included, so a host method defined in the class
    # body overrides it.
    module Generated
      REQUIRED_COLUMNS = {
        maquina_stream_buffer: :buffer,
        maquina_stream_append: :buffer,
        maquina_stream_sequence: SEQUENCE_COLUMN,
        maquina_stream_open?: STATUS_COLUMN,
        maquina_stream_seal!: STATUS_COLUMN
      }.freeze

      def maquina_stream_id
        to_param.to_s
      end

      def maquina_stream_buffer
        maquina_stream_read(buffer_column, :maquina_stream_buffer).to_s
      end

      def maquina_stream_append(text)
        column = buffer_column
        maquina_stream_require_column!(column, :maquina_stream_append)
        update!(column => "#{public_send(column)}#{text}")
        maquina_stream_buffer
      end

      def maquina_stream_sequence
        maquina_stream_read(SEQUENCE_COLUMN, :maquina_stream_sequence).to_i
      end

      # Added in Phase 3. The sequence is documented as "incremented per frame",
      # but the Broadcaster cannot write host state directly without
      # contradicting "host owns persistence" - so it asks, through the
      # contract, and the host's database does the incrementing atomically.
      # That is also what keeps it monotonic under concurrent appends.
      def maquina_stream_advance
        maquina_stream_require_column!(SEQUENCE_COLUMN, :maquina_stream_advance)
        self.class.where(id: id).update_all("#{SEQUENCE_COLUMN} = #{SEQUENCE_COLUMN} + 1")
        reload.maquina_stream_sequence
      end

      # The recorded end state, for replay and export. Nil while still open.
      def maquina_stream_status
        return nil if maquina_stream_open?

        maquina_stream_read(STATUS_COLUMN, :maquina_stream_status)&.to_sym
      end

      def maquina_stream_open?
        maquina_stream_read(STATUS_COLUMN, :maquina_stream_open?).to_s == OPEN_STATUS
      end

      def maquina_stream_seal!(status: :complete)
        unless SEAL_STATUSES.include?(status.to_sym)
          raise ArgumentError, "status must be one of #{SEAL_STATUSES.join(", ")}, got #{status.inspect}"
        end

        maquina_stream_require_column!(STATUS_COLUMN, :maquina_stream_seal!)
        update!(STATUS_COLUMN => status.to_s)
        status.to_sym
      end

      def maquina_stream_target
        resolver = self.class.maquina_stream_target_resolver
        unless resolver.respond_to?(:call)
          raise ContractError, <<~MESSAGE
            #{self.class.name} does not supply #maquina_stream_target: `stream_for:`
            is not callable. The broadcast target belongs to the host — the engine
            never guesses one. See docs/engine-contract.md.
          MESSAGE
        end

        resolver.call(self)
      end

      private
        def buffer_column
          self.class.maquina_stream_buffer_column
        end

        def maquina_stream_read(column, method)
          maquina_stream_require_column!(column, method)
          public_send(column)
        end

        def maquina_stream_require_column!(column, method)
          return if self.class.maquina_stream_column?(column)

          raise ContractError, <<~MESSAGE
            #{self.class.name} does not satisfy MaquinaStream::Streamable: ##{method}
            needs a `#{column}` column, and #{self.class.name} has none. Add the column,
            or define ##{method} on #{self.class.name} yourself.
            See docs/engine-contract.md.
          MESSAGE
        end
    end
  end
end
