# frozen_string_literal: true

require "rouge"

module MaquinaStream
  # Two stylesheets, one per scheme, generated from the Rouge themes named in
  # the configuration.
  #
  # Highlighting emits classes and never inline colour, so switching to dark
  # mode is a stylesheet concern and needs no re-render — which matters, because
  # a re-render mid-stream would mean re-broadcasting sealed blocks to change a
  # colour.
  module Themes
    SCOPE = "[data-ms-code]"
    DARK_SELECTOR = '[data-theme="dark"]'
    LIGHT_SELECTOR = ':root:not([data-theme="dark"])'

    class UnknownTheme < Error; end

    class << self
      def stylesheet(scheme, config: MaquinaStream.config)
        case scheme.to_sym
        when :light then light(config)
        when :dark then dark(config)
        else raise ArgumentError, "scheme must be :light or :dark"
        end
      end

      def path(scheme)
        File.expand_path("../../app/assets/stylesheets/maquina_stream/themes/#{scheme}.css", __dir__)
      end

      private
        def light(config)
          <<~CSS
            /* Generated by `rake maquina_stream:themes`. Do not edit by hand. */
            #{render(config.themes.fetch(:light), "#{LIGHT_SELECTOR} #{SCOPE}")}
          CSS
        end

        # The dark rules are written twice on purpose: once behind the media
        # query for a viewer who never chose, and once behind the explicit
        # attribute so a chosen theme beats the system preference.
        def dark(config)
          rules = render(config.themes.fetch(:dark), "#{DARK_SELECTOR} #{SCOPE}")
          system = render(config.themes.fetch(:dark), ":root:not([data-theme=\"light\"]) #{SCOPE}")

          <<~CSS
            /* Generated by `rake maquina_stream:themes`. Do not edit by hand. */
            #{rules}
            @media (prefers-color-scheme: dark) {
            #{system}
            }
          CSS
        end

        def render(name, scope)
          theme = Rouge::Theme.find(name.to_s)
          raise UnknownTheme, "Rouge has no theme named #{name.inspect}" unless theme

          theme.render(scope: scope)
        end
    end
  end
end
